spring:
  application:
    name: food-machine

  datasource:
    url: jdbc:h2:~/data/testdb
    # driverClassName: org.h2.Driver
    userName: sa
    password: sa
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
    h2:
      console:
        enabled: true

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

server:
  port: 9001


logging:
  level:
    org.springdoc: DEBUG